export const EVENTS = {
    // Dialogue / UI
    DIALOGUE_OPEN: 'DIALOGUE_OPEN',
    DIALOGUE_END: 'DIALOGUE_END',
    DIALOGUE_UI_OPENED: 'DIALOGUE_UI_OPENED',
    DIALOGUE_UI_CLOSED: 'DIALOGUE_UI_CLOSED',
    UI_TOGGLE_COMPANION_PANEL: 'UI_TOGGLE_COMPANION_PANEL',
    UI_TRAVEL_REQUESTED: 'UI_TRAVEL_REQUESTED',

    // World / exploration
    LOCATION_CHANGED: 'LOCATION_CHANGED',
    LOCATION_ENTERED: 'LOCATION_ENTERED',
    LOCATION_DISCOVERED: 'LOCATION_DISCOVERED',
    AREA_EXPLORED: 'AREA_EXPLORED',
    BUILDING_ENTERED: 'BUILDING_ENTERED',
    BUILDING_EXITED: 'BUILDING_EXITED',
    PORTAL_ENTERED: 'PORTAL_ENTERED',
    WORLD_STATE_CHANGED: 'WORLD_STATE_CHANGED',
    REWARD_GRANTED: 'REWARD_GRANTED',

    // Quest / mission lifecycle
    MISSION_STARTED: 'MISSION_STARTED',
    MISSION_COMPLETED: 'MISSION_COMPLETED',
    MISSION_FAILED: 'MISSION_FAILED',
    MISSION_PHASE_CHANGED: 'MISSION_PHASE_CHANGED',
    MISSION_INTERACTABLE_SPAWNED: 'MISSION_INTERACTABLE_SPAWNED',
    MISSION_MANAGER_READY: 'MISSION_MANAGER_READY',
    MISSION_RECORD_CREATED: 'MISSION_RECORD_CREATED',
    MISSION_STATE_CHANGED: 'MISSION_STATE_CHANGED',
    MISSION_STATE_LOG: 'MISSION_STATE_LOG',
    OBJECTIVE_PROGRESS_UPDATED: 'OBJECTIVE_PROGRESS_UPDATED',
    QUEST_PROGRESS_UPDATED: 'QUEST_PROGRESS_UPDATED',

    // Quest state events
    QUEST_OFFERED: 'QUEST_OFFERED',
    QUEST_ACCEPTED: 'QUEST_ACCEPTED',
    QUEST_ACTIVATED: 'QUEST_ACTIVATED',
    QUEST_COMPLETED: 'QUEST_COMPLETED',
    QUEST_ABANDONED: 'QUEST_ABANDONED',
    QUEST_PARTICIPANT_ADDED: 'QUEST_PARTICIPANT_ADDED',
    QUEST_OBJECTIVE_ADDED: 'QUEST_OBJECTIVE_ADDED',

    // Entities / interactions
    NPC_INTERACTION: 'NPC_INTERACTION',
    ITEM_COLLECTED: 'ITEM_COLLECTED',
    DELIVER_ITEM: 'DELIVER_ITEM',
    CUSTOM_ACTION: 'CUSTOM_ACTION',

    // Partners / companions
    CHARACTER_SWITCHED: 'CHARACTER_SWITCHED',
    PARTNER_SUMMONED: 'PARTNER_SUMMONED',
    COMPANION_CALLED: 'COMPANION_CALLED',
    COMPANION_ABILITY_USED: 'COMPANION_ABILITY_USED',
    COMPANIONS_RESET: 'COMPANIONS_RESET'
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];
