"""
Agents module for Super Wings Simulator.
Provides AI agents for mission dispatch, dialogue, narration, events, tutorials, and progress analysis.
"""

from .base_agent import (
    BaseAgent,
    SimpleReasoningAgent,
    AgentState,
    AgentMemory,
    AgentResponse,
    ReasoningMode,
    PlanStep,
    ExecutionPlan,
)
from .mission_dispatcher import (
    MissionDispatcherAgent,
    MissionRequest,
    DispatchRecommendation,
    get_dispatcher_agent,
)
from .character_dialogue import (
    CharacterDialogueAgent,
    DialogueRequest,
    NPCDialogueRequest,
    DialogueType,
    MissionPhase,
    get_dialogue_agent,
)
from .mission_narrator import (
    MissionNarratorAgent,
    NarrationPhase,
    NarrationRequest,
    Narration,
    get_narrator_agent,
)
from .event_generator import (
    EventGeneratorAgent,
    EventType,
    EventDifficulty,
    EventChoice,
    GameEvent,
    EventRequest,
    get_event_generator,
)
from .tutorial_agent import (
    TutorialAgent,
    TutorialType,
    TutorialRequest,
    TutorialHintRequest,
    TutorialResponse,
    get_tutorial_agent,
)
from .progress_analyzer import (
    ProgressAnalyzerAgent,
    AnalysisType,
    PlayerProgress,
    ProgressAnalysis,
    Recommendation,
    get_progress_agent,
)
from .comfyui_workflow import (
    ComfyUIWorkflowAgent,
    ComfyUIWorkflow,
    WorkflowStatus,
    WorkflowProgress,
    GenerationType,
    GenerationRequest,
    GenerationResult,
    get_comfyui_agent,
)
from .prompt_engineer import (
    PromptEngineerAgent,
    PromptCategory,
    ViewAngle,
    CharacterState,
    CharacterExpression,
    CharacterInfo,
    PromptRequest,
    EnhancedPrompt,
    get_prompt_agent,
)
from .character_image import (
    CharacterImageAgent,
    PortraitType,
    ImageCategory,
    CharacterImageRequest,
    CharacterImageResult,
    BatchGenerationRequest,
    BatchGenerationResult,
    get_character_image_agent,
)
from .background_generator import (
    BackgroundGeneratorAgent,
    SkyType,
    WorldLocation,
    BackgroundCategory,
    BackgroundRequest,
    BackgroundResult,
    BatchBackgroundResult,
    get_background_agent,
)
from .ui_asset_generator import (
    UIAssetGeneratorAgent,
    IconCategory,
    MissionIcon,
    ResourceIcon,
    AchievementIcon,
    ButtonType,
    UIElementType,
    UIAssetRequest,
    UIAssetResult,
    BatchUIAssetResult,
    get_ui_asset_agent,
)
from .transformation_image import (
    TransformationImageAgent,
    TransformationStage,
    TransformationEffect,
    TransformationRequest,
    TransformationResult,
    TransformationSequenceResult,
    get_transformation_agent,
)
from .scene_composer import (
    SceneComposerAgent,
    SceneType,
    LayerType,
    VisualEffect,
    CharacterPlacement,
    SceneRequest,
    SceneResult,
    get_scene_composer_agent,
)
from .voice_generator import (
    VoiceGeneratorAgent,
    VoiceEmotion,
    VoiceSpeed,
    VoiceRequest,
    VoiceResult,
    BatchVoiceResult,
    get_voice_agent,
)
from .sound_effect import (
    SoundEffectAgent,
    SoundCategory,
    UISoundType,
    FlightSoundType,
    TransformationSoundType,
    EnvironmentSoundType,
    ActionSoundType,
    CelebrationSoundType,
    SoundRequest,
    SoundResult,
    BatchSoundResult,
    get_sound_effect_agent,
)
from .animation_sequence import (
    AnimationSequenceAgent,
    AnimationType,
    EasingFunction,
    ExportFormat,
    AnimationKeyframe,
    AnimationTrack,
    AnimationPlan,
    AnimationRequest,
    AnimationResult,
    get_animation_agent,
)
from .mission_asset_packager import (
    MissionAssetPackagerAgent,
    AssetType,
    PackageQuality,
    MissionAssetConfig,
    AssetManifestItem,
    AssetManifest,
    PackageRequest,
    PackageResult,
    GenerationProgress,
    get_packager_agent,
)
from .content_generator import (
    ContentGeneratorAgent,
    GeneratedMission,
    GeneratedLocation,
    GeneratedEvent,
    get_content_generator,
)
from .npc_generator import (
    NPCGenerator,
    GeneratedNPC,
    get_npc_generator,
)

__all__ = [
    # Base Agent
    "BaseAgent",
    "SimpleReasoningAgent",
    "AgentState",
    "AgentMemory",
    "AgentResponse",
    "ReasoningMode",
    "PlanStep",
    "ExecutionPlan",
    # Mission Dispatcher
    "MissionDispatcherAgent",
    "MissionRequest",
    "DispatchRecommendation",
    "get_dispatcher_agent",
    # Character Dialogue
    "CharacterDialogueAgent",
    "DialogueRequest",
    "NPCDialogueRequest",
    "DialogueType",
    "MissionPhase",
    "get_dialogue_agent",
    # Mission Narrator
    "MissionNarratorAgent",
    "NarrationPhase",
    "NarrationRequest",
    "Narration",
    "get_narrator_agent",
    # Event Generator
    "EventGeneratorAgent",
    "EventType",
    "EventDifficulty",
    "EventChoice",
    "GameEvent",
    "EventRequest",
    "get_event_generator",
    # Tutorial Agent
    "TutorialAgent",
    "TutorialType",
    "TutorialRequest",
    "TutorialHintRequest",
    "TutorialResponse",
    "get_tutorial_agent",
    # Progress Analyzer
    "ProgressAnalyzerAgent",
    "AnalysisType",
    "PlayerProgress",
    "ProgressAnalysis",
    "Recommendation",
    "get_progress_agent",
    # ComfyUI Workflow Agent
    "ComfyUIWorkflowAgent",
    "ComfyUIWorkflow",
    "WorkflowStatus",
    "WorkflowProgress",
    "GenerationType",
    "GenerationRequest",
    "GenerationResult",
    "get_comfyui_agent",
    # Prompt Engineer Agent
    "PromptEngineerAgent",
    "PromptCategory",
    "ViewAngle",
    "CharacterState",
    "CharacterExpression",
    "CharacterInfo",
    "PromptRequest",
    "EnhancedPrompt",
    "get_prompt_agent",
    # Character Image Agent
    "CharacterImageAgent",
    "PortraitType",
    "ImageCategory",
    "CharacterImageRequest",
    "CharacterImageResult",
    "BatchGenerationRequest",
    "BatchGenerationResult",
    "get_character_image_agent",
    # Background Generator Agent
    "BackgroundGeneratorAgent",
    "SkyType",
    "WorldLocation",
    "BackgroundCategory",
    "BackgroundRequest",
    "BackgroundResult",
    "BatchBackgroundResult",
    "get_background_agent",
    # UI Asset Generator Agent
    "UIAssetGeneratorAgent",
    "IconCategory",
    "MissionIcon",
    "ResourceIcon",
    "AchievementIcon",
    "ButtonType",
    "UIElementType",
    "UIAssetRequest",
    "UIAssetResult",
    "BatchUIAssetResult",
    "get_ui_asset_agent",
    # Transformation Image Agent
    "TransformationImageAgent",
    "TransformationStage",
    "TransformationEffect",
    "TransformationRequest",
    "TransformationResult",
    "TransformationSequenceResult",
    "get_transformation_agent",
    # Scene Composer Agent
    "SceneComposerAgent",
    "SceneType",
    "LayerType",
    "VisualEffect",
    "CharacterPlacement",
    "SceneRequest",
    "SceneResult",
    "get_scene_composer_agent",
    # Voice Generator Agent
    "VoiceGeneratorAgent",
    "VoiceEmotion",
    "VoiceSpeed",
    "VoiceRequest",
    "VoiceResult",
    "BatchVoiceResult",
    "get_voice_agent",
    # Sound Effect Agent
    "SoundEffectAgent",
    "SoundCategory",
    "UISoundType",
    "FlightSoundType",
    "TransformationSoundType",
    "EnvironmentSoundType",
    "ActionSoundType",
    "CelebrationSoundType",
    "SoundRequest",
    "SoundResult",
    "BatchSoundResult",
    "get_sound_effect_agent",
    # Animation Sequence Agent
    "AnimationSequenceAgent",
    "AnimationType",
    "EasingFunction",
    "ExportFormat",
    "AnimationKeyframe",
    "AnimationTrack",
    "AnimationPlan",
    "AnimationRequest",
    "AnimationResult",
    "get_animation_agent",
    # Mission Asset Packager Agent
    "MissionAssetPackagerAgent",
    "AssetType",
    "PackageQuality",
    "MissionAssetConfig",
    "AssetManifestItem",
    "AssetManifest",
    "PackageRequest",
    "PackageResult",
    "GenerationProgress",
    "get_packager_agent",
    # Content Generator Agent
    "ContentGeneratorAgent",
    "GeneratedMission",
    "GeneratedLocation",
    "GeneratedEvent",
    "get_content_generator",
    # NPC Generator Agent
    "NPCGenerator",
    "GeneratedNPC",
    "get_npc_generator",
]
